version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/Devops1
    steps:
  #upgrade pip
      - checkout
      - run:
          name: Upgrade pip
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
          #2 create virtual environment and install dependencies -
      - run:
          name: Install dependencies
          command: |
              . venv/bin/activate
              pip install -r requirements.txt
          #3 run coding convention software and also the tester
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            flake8 –-exclude=venv* --statistics
            pytest --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results