version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/Devops1
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
      - run:
          name: Install dependencies
          command: |
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results


