# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference

# For a detailed guide to building and testing with Python, read the docs:
# https://circleci.com/docs/language-python/ for more details
version: 2.1
jobs:
      build:
            docker:
                    - image: circleci/python:3.12
      #Specify working directory, the directory name is the title of the repo
            working_directory: ~/Devops1
    # Add steps to the job
            steps:
                  #1 Obtain repo from Github
                  - checkout
                  #2 Create a virtual environment and install dependencies
                  - run:
                        name: Install dependencies
                        command: |
                               python3 -m venv venv
                               . venv/bin/activate
                               pip install -r requirements.txt
                  #3 Run coding convention software plus tester.
                  - run:
                        name: Run tests
                        command: |
                               . venv/bin/activate
                               flake8 --exclude=venv* --statistics
                               # pytest -v --cov=calculator
                               pytest --junitxml=test-results/junit.xml
                  - store_test_results:
                        path: test-results
                  - store_artifacts:
                        path: test-results